// flow-typed signature: f51740ad9d7e8597b0e29875406a4dd4
// flow-typed version: <<STUB>>/apollo-tracing_v^0.0.9/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-tracing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-tracing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-tracing/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-tracing/lib/instrumentation' {
  declare module.exports: any;
}

declare module 'apollo-tracing/lib/tracingFormat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-tracing/lib/index.js' {
  declare module.exports: $Exports<'apollo-tracing/lib/index'>;
}
declare module 'apollo-tracing/lib/instrumentation.js' {
  declare module.exports: $Exports<'apollo-tracing/lib/instrumentation'>;
}
declare module 'apollo-tracing/lib/tracingFormat.js' {
  declare module.exports: $Exports<'apollo-tracing/lib/tracingFormat'>;
}
