// flow-typed signature: ed92ed7d1dd1cacf7339779f72aa7ee3
// flow-typed version: <<STUB>>/apollo-cache-redux_v^0.1.0-alpha.7/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-cache-redux'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-cache-redux' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-cache-redux/lib/constants' {
  declare module.exports: any;
}

declare module 'apollo-cache-redux/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-cache-redux/lib/reducer' {
  declare module.exports: any;
}

declare module 'apollo-cache-redux/lib/reduxCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-redux/lib/reduxNormalizedCache' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-cache-redux/lib/constants.js' {
  declare module.exports: $Exports<'apollo-cache-redux/lib/constants'>;
}
declare module 'apollo-cache-redux/lib/index.js' {
  declare module.exports: $Exports<'apollo-cache-redux/lib/index'>;
}
declare module 'apollo-cache-redux/lib/reducer.js' {
  declare module.exports: $Exports<'apollo-cache-redux/lib/reducer'>;
}
declare module 'apollo-cache-redux/lib/reduxCache.js' {
  declare module.exports: $Exports<'apollo-cache-redux/lib/reduxCache'>;
}
declare module 'apollo-cache-redux/lib/reduxNormalizedCache.js' {
  declare module.exports: $Exports<'apollo-cache-redux/lib/reduxNormalizedCache'>;
}
