// flow-typed signature: 6b3692f519e4ba05615c3a56fa66315b
// flow-typed version: <<STUB>>/autodll-webpack-plugin_v^0.0.7/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autodll-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autodll-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autodll-webpack-plugin/examples/basic/src/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/basic/webpack.config' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/minification/src/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/minification/webpack.config' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/performance/src/App' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/performance/src/TestMoment' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/performance/src/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/performance/webpack.config' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/recommended/src/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/examples/recommended/webpack.config' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/compileIfNeeded' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createCompiler' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createConfig' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createLogger' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/createMemory' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/normalizeEntry' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/paths' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/plugin' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/utils/fs' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/lib/utils/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/specs/compileIfNeeded.spec' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/specs/createConfig.spec' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/specs/createMemory.spec' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/specs/normalizeEntry.spec' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/specs/pluginSupport.spec' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/compileIfNeeded' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createCompiler' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createConfig' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createLogger' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/createMemory' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/index' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/normalizeEntry' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/paths' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/plugin' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/utils/fs' {
  declare module.exports: any;
}

declare module 'autodll-webpack-plugin/src/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autodll-webpack-plugin/examples/basic/src/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/basic/src/index'>;
}
declare module 'autodll-webpack-plugin/examples/basic/webpack.config.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/basic/webpack.config'>;
}
declare module 'autodll-webpack-plugin/examples/minification/src/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/minification/src/index'>;
}
declare module 'autodll-webpack-plugin/examples/minification/webpack.config.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/minification/webpack.config'>;
}
declare module 'autodll-webpack-plugin/examples/performance/src/App.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/performance/src/App'>;
}
declare module 'autodll-webpack-plugin/examples/performance/src/TestMoment.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/performance/src/TestMoment'>;
}
declare module 'autodll-webpack-plugin/examples/performance/src/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/performance/src/index'>;
}
declare module 'autodll-webpack-plugin/examples/performance/webpack.config.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/performance/webpack.config'>;
}
declare module 'autodll-webpack-plugin/examples/recommended/src/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/recommended/src/index'>;
}
declare module 'autodll-webpack-plugin/examples/recommended/webpack.config.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/examples/recommended/webpack.config'>;
}
declare module 'autodll-webpack-plugin/lib/compileIfNeeded.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/compileIfNeeded'>;
}
declare module 'autodll-webpack-plugin/lib/createCompiler.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createCompiler'>;
}
declare module 'autodll-webpack-plugin/lib/createConfig.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createConfig'>;
}
declare module 'autodll-webpack-plugin/lib/createLogger.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createLogger'>;
}
declare module 'autodll-webpack-plugin/lib/createMemory.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/createMemory'>;
}
declare module 'autodll-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/index'>;
}
declare module 'autodll-webpack-plugin/lib/normalizeEntry.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/normalizeEntry'>;
}
declare module 'autodll-webpack-plugin/lib/paths.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/paths'>;
}
declare module 'autodll-webpack-plugin/lib/plugin.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/plugin'>;
}
declare module 'autodll-webpack-plugin/lib/utils/fs.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/utils/fs'>;
}
declare module 'autodll-webpack-plugin/lib/utils/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/lib/utils/index'>;
}
declare module 'autodll-webpack-plugin/specs/compileIfNeeded.spec.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/specs/compileIfNeeded.spec'>;
}
declare module 'autodll-webpack-plugin/specs/createConfig.spec.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/specs/createConfig.spec'>;
}
declare module 'autodll-webpack-plugin/specs/createMemory.spec.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/specs/createMemory.spec'>;
}
declare module 'autodll-webpack-plugin/specs/normalizeEntry.spec.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/specs/normalizeEntry.spec'>;
}
declare module 'autodll-webpack-plugin/specs/pluginSupport.spec.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/specs/pluginSupport.spec'>;
}
declare module 'autodll-webpack-plugin/src/compileIfNeeded.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/compileIfNeeded'>;
}
declare module 'autodll-webpack-plugin/src/createCompiler.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createCompiler'>;
}
declare module 'autodll-webpack-plugin/src/createConfig.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createConfig'>;
}
declare module 'autodll-webpack-plugin/src/createLogger.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createLogger'>;
}
declare module 'autodll-webpack-plugin/src/createMemory.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/createMemory'>;
}
declare module 'autodll-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/index'>;
}
declare module 'autodll-webpack-plugin/src/normalizeEntry.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/normalizeEntry'>;
}
declare module 'autodll-webpack-plugin/src/paths.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/paths'>;
}
declare module 'autodll-webpack-plugin/src/plugin.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/plugin'>;
}
declare module 'autodll-webpack-plugin/src/utils/fs.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/utils/fs'>;
}
declare module 'autodll-webpack-plugin/src/utils/index.js' {
  declare module.exports: $Exports<'autodll-webpack-plugin/src/utils/index'>;
}
