// flow-typed signature: 301ce39e2523da0920b42dcafcc24121
// flow-typed version: <<STUB>>/babel-plugin-graphql-tag_v^1.3.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-graphql-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-graphql-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-graphql-tag/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-graphql-tag/dist/index.js' {
  declare module.exports: $Exports<'babel-plugin-graphql-tag/dist/index'>;
}
