// flow-typed signature: 4718238627b2ea561df174e329df17e9
// flow-typed version: <<STUB>>/default-passive-events_v^1.0.7/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'default-passive-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'default-passive-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'default-passive-events/dist/index' {
  declare module.exports: any;
}

declare module 'default-passive-events/src/index' {
  declare module.exports: any;
}

declare module 'default-passive-events/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'default-passive-events/dist/index.js' {
  declare module.exports: $Exports<'default-passive-events/dist/index'>;
}
declare module 'default-passive-events/src/index.js' {
  declare module.exports: $Exports<'default-passive-events/src/index'>;
}
declare module 'default-passive-events/src/utils.js' {
  declare module.exports: $Exports<'default-passive-events/src/utils'>;
}
