// flow-typed signature: 8cc4a12fdbc80d368df793280485772b
// flow-typed version: <<STUB>>/default-passive-events_v^0.1.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'default-passive-events'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'default-passive-events' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'default-passive-events/default-passive-events' {
  declare module.exports: any;
}

// Filename aliases
declare module 'default-passive-events/default-passive-events.js' {
  declare module.exports: $Exports<'default-passive-events/default-passive-events'>;
}
