// flow-typed signature: 0684b4ada78fd802c17a7244cda2cb77
// flow-typed version: <<STUB>>/graphql-to-json_v^1.1.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-to-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-to-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-to-json/bin/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-to-json/bin/bin.js' {
  declare module.exports: $Exports<'graphql-to-json/bin/bin'>;
}
declare module 'graphql-to-json/index' {
  declare module.exports: $Exports<'graphql-to-json'>;
}
declare module 'graphql-to-json/index.js' {
  declare module.exports: $Exports<'graphql-to-json'>;
}
