// flow-typed signature: fbd966dc414ba210c3db84d534fac77b
// flow-typed version: <<STUB>>/multi-loader_v^0.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multi-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multi-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multi-loader/example/bundle' {
  declare module.exports: any;
}

declare module 'multi-loader/example/test' {
  declare module.exports: any;
}

declare module 'multi-loader/example/webpack.config' {
  declare module.exports: any;
}

declare module 'multi-loader/index.loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multi-loader/example/bundle.js' {
  declare module.exports: $Exports<'multi-loader/example/bundle'>;
}
declare module 'multi-loader/example/test.js' {
  declare module.exports: $Exports<'multi-loader/example/test'>;
}
declare module 'multi-loader/example/webpack.config.js' {
  declare module.exports: $Exports<'multi-loader/example/webpack.config'>;
}
declare module 'multi-loader/index' {
  declare module.exports: $Exports<'multi-loader'>;
}
declare module 'multi-loader/index.js' {
  declare module.exports: $Exports<'multi-loader'>;
}
declare module 'multi-loader/index.loader.js' {
  declare module.exports: $Exports<'multi-loader/index.loader'>;
}
