// flow-typed signature: 7a16cc13f62c46cd1928a9d82e46c607
// flow-typed version: <<STUB>>/passport-custom_v^1.0.5/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-custom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-custom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-custom/lib/index' {
  declare module.exports: any;
}

declare module 'passport-custom/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-custom/lib/index.js' {
  declare module.exports: $Exports<'passport-custom/lib/index'>;
}
declare module 'passport-custom/lib/strategy.js' {
  declare module.exports: $Exports<'passport-custom/lib/strategy'>;
}
