// flow-typed signature: 88982a55b8f30f173b02a65606c2c2f7
// flow-typed version: <<STUB>>/passport-linkedin_v^1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-linkedin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-linkedin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-linkedin/lib/index' {
  declare module.exports: any;
}

declare module 'passport-linkedin/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-linkedin/lib/index.js' {
  declare module.exports: $Exports<'passport-linkedin/lib/index'>;
}
declare module 'passport-linkedin/lib/strategy.js' {
  declare module.exports: $Exports<'passport-linkedin/lib/strategy'>;
}
