// flow-typed signature: 2ec5b5d90af926e0a693f2fc557a3961
// flow-typed version: <<STUB>>/passport-oauth2-password-grant_v^0.0.4/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-oauth2-password-grant'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-oauth2-password-grant' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-oauth2-password-grant/lib/index' {
  declare module.exports: any;
}

declare module 'passport-oauth2-password-grant/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-oauth2-password-grant/lib/index.js' {
  declare module.exports: $Exports<'passport-oauth2-password-grant/lib/index'>;
}
declare module 'passport-oauth2-password-grant/lib/strategy.js' {
  declare module.exports: $Exports<'passport-oauth2-password-grant/lib/strategy'>;
}
