// flow-typed signature: d846eea6a26a451cab2da9a9188138b4
// flow-typed version: <<STUB>>/react-perf-devtool_v^3.0.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-perf-devtool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-perf-devtool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-perf-devtool/src/extension/components/ErrorComponent' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/ReactPerfDevtool' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/Results' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/Table' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/TableData' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/extension/components/TableHeader' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/index' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/npm/hook' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/npm/index' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/commitChanges' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/generate' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/hostEffects' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/lifecycle' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/math' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/parse' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/parseMeasures' {
  declare module.exports: any;
}

declare module 'react-perf-devtool/src/shared/totalTime' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-perf-devtool/src/extension/components/ErrorComponent.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/ErrorComponent'>;
}
declare module 'react-perf-devtool/src/extension/components/ReactPerfDevtool.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/ReactPerfDevtool'>;
}
declare module 'react-perf-devtool/src/extension/components/Results.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/Results'>;
}
declare module 'react-perf-devtool/src/extension/components/Table.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/Table'>;
}
declare module 'react-perf-devtool/src/extension/components/TableData.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/TableData'>;
}
declare module 'react-perf-devtool/src/extension/components/TableHeader.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/extension/components/TableHeader'>;
}
declare module 'react-perf-devtool/src/index.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/index'>;
}
declare module 'react-perf-devtool/src/npm/hook.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/npm/hook'>;
}
declare module 'react-perf-devtool/src/npm/index.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/npm/index'>;
}
declare module 'react-perf-devtool/src/shared/commitChanges.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/commitChanges'>;
}
declare module 'react-perf-devtool/src/shared/generate.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/generate'>;
}
declare module 'react-perf-devtool/src/shared/hostEffects.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/hostEffects'>;
}
declare module 'react-perf-devtool/src/shared/lifecycle.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/lifecycle'>;
}
declare module 'react-perf-devtool/src/shared/math.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/math'>;
}
declare module 'react-perf-devtool/src/shared/parse.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/parse'>;
}
declare module 'react-perf-devtool/src/shared/parseMeasures.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/parseMeasures'>;
}
declare module 'react-perf-devtool/src/shared/totalTime.js' {
  declare module.exports: $Exports<'react-perf-devtool/src/shared/totalTime'>;
}
