// flow-typed signature: d9a7262bbe6d5bb59be94ece6a1edb57
// flow-typed version: <<STUB>>/react-network_v^1.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-network'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-network' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-network/es/index' {
  declare module.exports: any;
}

declare module 'react-network/lib/index' {
  declare module.exports: any;
}

declare module 'react-network/umd/react-network' {
  declare module.exports: any;
}

declare module 'react-network/umd/react-network.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-network/es/index.js' {
  declare module.exports: $Exports<'react-network/es/index'>;
}
declare module 'react-network/lib/index.js' {
  declare module.exports: $Exports<'react-network/lib/index'>;
}
declare module 'react-network/umd/react-network.js' {
  declare module.exports: $Exports<'react-network/umd/react-network'>;
}
declare module 'react-network/umd/react-network.min.js' {
  declare module.exports: $Exports<'react-network/umd/react-network.min'>;
}
