// flow-typed signature: 5cb809da3b83e8e7995249c1733566b8
// flow-typed version: <<STUB>>/react-image-webp_v^0.2.2/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-image-webp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-image-webp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-image-webp/dist/index' {
  declare module.exports: any;
}

declare module 'react-image-webp/examples/dist/index' {
  declare module.exports: any;
}

declare module 'react-image-webp/examples/modules/index' {
  declare module.exports: any;
}

declare module 'react-image-webp/examples/webpack.config' {
  declare module.exports: any;
}

declare module 'react-image-webp/modules/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-image-webp/dist/index.js' {
  declare module.exports: $Exports<'react-image-webp/dist/index'>;
}
declare module 'react-image-webp/examples/dist/index.js' {
  declare module.exports: $Exports<'react-image-webp/examples/dist/index'>;
}
declare module 'react-image-webp/examples/modules/index.js' {
  declare module.exports: $Exports<'react-image-webp/examples/modules/index'>;
}
declare module 'react-image-webp/examples/webpack.config.js' {
  declare module.exports: $Exports<'react-image-webp/examples/webpack.config'>;
}
declare module 'react-image-webp/modules/index.js' {
  declare module.exports: $Exports<'react-image-webp/modules/index'>;
}
