// flow-typed signature: 96f1b10917f48942e9f669e25e04a4b4
// flow-typed version: <<STUB>>/react-ckeditor-component_v^1.0.7/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ckeditor-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ckeditor-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ckeditor-component/lib/ckeditor' {
  declare module.exports: any;
}

declare module 'react-ckeditor-component/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ckeditor-component/lib/ckeditor.js' {
  declare module.exports: $Exports<'react-ckeditor-component/lib/ckeditor'>;
}
declare module 'react-ckeditor-component/lib/index.js' {
  declare module.exports: $Exports<'react-ckeditor-component/lib/index'>;
}
