// flow-typed signature: 1bc7351ce62e03643fae73f913fce6f1
// flow-typed version: <<STUB>>/react-services-injector_v^1.0.0-rc.3/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-services-injector'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-services-injector' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-services-injector/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-services-injector/dist/index.js' {
  declare module.exports: $Exports<'react-services-injector/dist/index'>;
}
declare module 'react-services-injector/index' {
  declare module.exports: $Exports<'react-services-injector'>;
}
declare module 'react-services-injector/index.js' {
  declare module.exports: $Exports<'react-services-injector'>;
}
