// flow-typed signature: 312245b578c7c9347c1b3163804d98bb
// flow-typed version: <<STUB>>/redux-first-router-restore-scroll_v^1.2.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-first-router-restore-scroll'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-first-router-restore-scroll' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-first-router-restore-scroll/dist/index' {
  declare module.exports: any;
}

declare module 'redux-first-router-restore-scroll/dist/redux-first-router-restore-scroll' {
  declare module.exports: any;
}

declare module 'redux-first-router-restore-scroll/dist/redux-first-router-restore-scroll.min' {
  declare module.exports: any;
}

declare module 'redux-first-router-restore-scroll/dist/SessionStorage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-first-router-restore-scroll/dist/index.js' {
  declare module.exports: $Exports<'redux-first-router-restore-scroll/dist/index'>;
}
declare module 'redux-first-router-restore-scroll/dist/redux-first-router-restore-scroll.js' {
  declare module.exports: $Exports<'redux-first-router-restore-scroll/dist/redux-first-router-restore-scroll'>;
}
declare module 'redux-first-router-restore-scroll/dist/redux-first-router-restore-scroll.min.js' {
  declare module.exports: $Exports<'redux-first-router-restore-scroll/dist/redux-first-router-restore-scroll.min'>;
}
declare module 'redux-first-router-restore-scroll/dist/SessionStorage.js' {
  declare module.exports: $Exports<'redux-first-router-restore-scroll/dist/SessionStorage'>;
}
