// flow-typed signature: 587de38cd9eeaa42e0c2200c270f611e
// flow-typed version: <<STUB>>/simple-line-icons_v^2.4.1/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-line-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-line-icons' {
  declare module.exports: any;
}
