// flow-typed signature: e73f12364bf3e716984fe6ecd74f8d4a
// flow-typed version: <<STUB>>/simple-line-icons_v^2.4.1/flow_v0.53.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-line-icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-line-icons' {
  declare module.exports: any;
}
