// flow-typed signature: 150e3493ab8d36292a9af23051536880
// flow-typed version: <<STUB>>/tinycon_v^0.6.8/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tinycon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tinycon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tinycon/examples/require' {
  declare module.exports: any;
}

declare module 'tinycon/Gruntfile' {
  declare module.exports: any;
}

declare module 'tinycon/tinycon' {
  declare module.exports: any;
}

declare module 'tinycon/tinycon.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tinycon/examples/require.js' {
  declare module.exports: $Exports<'tinycon/examples/require'>;
}
declare module 'tinycon/Gruntfile.js' {
  declare module.exports: $Exports<'tinycon/Gruntfile'>;
}
declare module 'tinycon/tinycon.js' {
  declare module.exports: $Exports<'tinycon/tinycon'>;
}
declare module 'tinycon/tinycon.min.js' {
  declare module.exports: $Exports<'tinycon/tinycon.min'>;
}
