// flow-typed signature: 674da078ff45ffaad6c72ed8eb651972
// flow-typed version: <<STUB>>/trim_v^0.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'trim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'trim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'trim/index' {
  declare module.exports: $Exports<'trim'>;
}
declare module 'trim/index.js' {
  declare module.exports: $Exports<'trim'>;
}
