// flow-typed signature: 4de728a57a2867512ca93d7f1daa0efb
// flow-typed version: <<STUB>>/webp-loader_v^0.2.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webp-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webp-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webp-loader/index' {
  declare module.exports: $Exports<'webp-loader'>;
}
declare module 'webp-loader/index.js' {
  declare module.exports: $Exports<'webp-loader'>;
}
