// flow-typed signature: cca9c991a82dcf63497f55f1010e77a4
// flow-typed version: <<STUB>>/webpack-dotenv-plugin_v^2.0.2/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dotenv-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dotenv-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'webpack-dotenv-plugin/index' {
  declare module.exports: $Exports<'webpack-dotenv-plugin'>;
}
declare module 'webpack-dotenv-plugin/index.js' {
  declare module.exports: $Exports<'webpack-dotenv-plugin'>;
}
