version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get install python-dev && curl -O https://bootstrap.pypa.io/get-pip.py && python get-pip.py --user && echo "export PATH=~/.local/bin:$PATH" >> ~/.bashrc && export PATH=~/.local/bin:$PATH && pip install awscli --upgrade --user
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Project Dependencies
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests, Linting, and Flow
          command: yarn suite
      - deploy:
          name: Deploy to AWS OpsWorks
          command: |
            if [ -z ${STACK_ID} ]; then
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                export PATH=~/.local/bin:$PATH && aws opsworks --region "us-east-1" create-deployment --stack-id ${STACK_ID} --app-id ${APP_ID} --layer-ids "${LAYER_ID}" --command "{\"Name\":\"deploy\"}";
              else
                  echo "Not master branch so not deploying"
              fi
            fi
