version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
        environment:
          AWS_ACCESS_KEY_ID: AKIAJJOHJYADZDECWBFQ
          AWS_SECRET_ACCESS_KEY: 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
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: 'sudo apt-get install awscli -y'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Project Dependencies
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests, Linting, and Flow
          command: yarn suite
      - deploy:
          name: Deploy to AWS OpsWorks
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./.circleci/opsworks.sh ae7b0c94-0237-42d1-bb47-f6f280f0d644 a46af8b6-4102-4428-8ab5-f360f54adef3
            else
                echo "Not master branch so not deploying"
            fi
