version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Install AWS CLI
          command: 'sudo apt-get install awscli -y'
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install Project Dependencies
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run Tests, Linting, and Flow
          command: yarn suite
      - deploy:
          name: Deploy to AWS OpsWorks
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./.circleci/opsworks.sh ${STACK_ID} ${APP_ID}
            else
                echo "Not master branch so not deploying"
            fi
