query CurrentUser {
  user {
    user_id
    uuid
    goal
    external_id
    bio
    prefix
    first_name
    last_name
    username
    mail
    status
    created
    changed
    last_login
    roles
  }
}
